version: '3.8'

services:
  # Restate server (durable execution engine)
  # This is the only service that needs to run in Docker
  # The application runs locally via: uv run uvicorn app.main:app --reload
  restate:
    image: restatedev/restate:latest
    ports:
      - "8080:8080"  # Restate HTTP endpoint
      - "9070:9070"  # Restate admin API
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - RUST_LOG=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9070/health"]
      interval: 10s
      timeout: 5s
      retries: 5
